import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();

const run = (command, fallback = '') => {
  try {
    return execSync(command, { cwd: repoRoot, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return fallback;
  }
};

const packageJsonPath = path.join(repoRoot, 'package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
const packageVersion = packageJson.version ?? '0.0.0';

const commitHash = run('git rev-parse HEAD', 'unknown');
const commitShort = run('git rev-parse --short HEAD', 'unknown');
const branch = run('git rev-parse --abbrev-ref HEAD', 'unknown');
const describe = run('git describe --always --dirty --tags', commitShort);

const logRaw = run('git log --date=iso-strict --pretty=format:%H%x1f%h%x1f%cI%x1f%ct%x1f%s -n 20', '');
const changelogEntries = logRaw
  .split('\n')
  .filter(Boolean)
  .map((line) => {
    const [hash, shortHash, timestamp, unixRaw, title] = line.split('\x1f');
    const unixTime = Number.parseInt(unixRaw, 10);
    return {
      hash,
      shortHash,
      date: timestamp.slice(0, 10),
      timestamp,
      unixTime: Number.isNaN(unixTime) ? 0 : unixTime,
      title
    };
  });

const [latest = null, ...history] = changelogEntries;

const snapshot = {
  generatedAt: new Date().toISOString(),
  packageVersion,
  commitHash,
  commitShort,
  branch,
  describe,
  label: `v${packageVersion} (${describe})`,
  latest,
  history
};

const output = `// Generated by scripts/generate_version_snapshot.mjs. Do not edit manually.

export interface VersionChangelogEntry {
  hash: string;
  shortHash: string;
  date: string;
  timestamp: string;
  unixTime: number;
  title: string;
}

export interface VersionSnapshot {
  generatedAt: string;
  packageVersion: string;
  commitHash: string;
  commitShort: string;
  branch: string;
  describe: string;
  label: string;
  latest: VersionChangelogEntry | null;
  history: VersionChangelogEntry[];
}

export const VERSION_SNAPSHOT: VersionSnapshot = ${JSON.stringify(snapshot, null, 2)};
`;

const outputPath = path.join(repoRoot, 'src/lib/data/version-snapshot.ts');
writeFileSync(outputPath, output, 'utf8');
console.log(`Wrote ${path.relative(repoRoot, outputPath)}`);
