// Generated by scripts/generate_version_snapshot.mjs. Do not edit manually.

export interface VersionChangelogEntry {
  hash: string;
  shortHash: string;
  date: string;
  timestamp: string;
  unixTime: number;
  title: string;
}

export interface VersionSnapshot {
  generatedAt: string;
  packageVersion: string;
  commitHash: string;
  commitShort: string;
  branch: string;
  describe: string;
  label: string;
  latest: VersionChangelogEntry | null;
  history: VersionChangelogEntry[];
}

export const VERSION_SNAPSHOT: VersionSnapshot = {
  "generatedAt": "2026-02-19T17:26:16.460Z",
  "packageVersion": "0.1.0",
  "commitHash": "1975cb6b1c508534e1fda870ae534e4aa0ad42e9",
  "commitShort": "1975cb6",
  "branch": "codex/sites-extra-info-mainline",
  "describe": "1975cb6-dirty",
  "label": "v0.1.0 (1975cb6-dirty)",
  "latest": {
    "hash": "1975cb6b1c508534e1fda870ae534e4aa0ad42e9",
    "shortHash": "1975cb6",
    "date": "2026-02-19",
    "timestamp": "2026-02-19T16:54:29+00:00",
    "unixTime": 1771520069,
    "title": "Generate 4 per-blueprint examples for every site page"
  },
  "history": [
    {
      "hash": "201117396265d290d65bef43fb983e82d34657c7",
      "shortHash": "2011173",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T16:41:57+00:00",
      "unixTime": 1771519317,
      "title": "Add bottom classroom ideas section to sites timeline page"
    },
    {
      "hash": "1af19c729742d09fed03bf8ba667f7e9d3f5df64",
      "shortHash": "1af19c7",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T16:32:54+00:00",
      "unixTime": 1771518774,
      "title": "Add 16 illustrated feature blueprints for site facts"
    },
    {
      "hash": "93bdc48070be97fc94b1ef6559085190cebdd7e5",
      "shortHash": "93bdc48",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T08:14:19-08:00",
      "unixTime": 1771517659,
      "title": "Automate build-time /version snapshot generation"
    },
    {
      "hash": "76869ba3378fe38461382520235ed2c2e102ad8f",
      "shortHash": "76869ba",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T15:33:44+00:00",
      "unixTime": 1771515224,
      "title": "Move materials and tools references below gallery"
    },
    {
      "hash": "f0153a0b726a21a7e64a2a2a4b3506026d89e296",
      "shortHash": "f0153a0",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T15:29:11+00:00",
      "unixTime": 1771514951,
      "title": "Remove extra info link from sites landing page"
    },
    {
      "hash": "e2fb0fc8eae83e865be4b2bd15c1f7db53b29ada",
      "shortHash": "e2fb0fc",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T15:11:49+00:00",
      "unixTime": 1771513909,
      "title": "Enable fullscreen lightbox for all site page images"
    },
    {
      "hash": "5ebb7317329619ff4dd17d9faba2e3b1fa19a3d7",
      "shortHash": "5ebb731",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T14:42:00+00:00",
      "unixTime": 1771512120,
      "title": "Add professional per-site visual dossiers with official and created references"
    },
    {
      "hash": "4d124f252047b351ae30e2ce4228c80463742bc7",
      "shortHash": "4d124f2",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T14:00:21+00:00",
      "unixTime": 1771509621,
      "title": "Rename extra info title to Developer Notes"
    },
    {
      "hash": "ee57ecef965dce9b0a2266ed4d81e2c02669d13b",
      "shortHash": "ee57ece",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T13:14:37+00:00",
      "unixTime": 1771506877,
      "title": "Add /sites/extra/info reference page and link from timeline"
    },
    {
      "hash": "ffe99aef78025d59ee61a78f4e9d90cc6fed85eb",
      "shortHash": "ffe99ae",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T05:02:32-08:00",
      "unixTime": 1771506152,
      "title": "Apply latest touch override and iPhone hotbar safe-area verification"
    }
  ]
};
