// Generated by scripts/generate_version_snapshot.mjs. Do not edit manually.

export interface VersionChangelogEntry {
  hash: string;
  shortHash: string;
  date: string;
  title: string;
}

export interface VersionSnapshot {
  generatedAt: string;
  packageVersion: string;
  commitHash: string;
  commitShort: string;
  branch: string;
  describe: string;
  label: string;
  latest: VersionChangelogEntry | null;
  history: VersionChangelogEntry[];
}

export const VERSION_SNAPSHOT: VersionSnapshot = {
  "generatedAt": "2026-02-18T12:18:03.796Z",
  "packageVersion": "0.1.0",
  "commitHash": "1ac5cd64fdd4c11488509a6f858ee3ec40dcedef",
  "commitShort": "1ac5cd6",
  "branch": "main",
  "describe": "1ac5cd6-dirty",
  "label": "v0.1.0 (1ac5cd6-dirty)",
  "latest": {
    "hash": "1ac5cd64fdd4c11488509a6f858ee3ec40dcedef",
    "shortHash": "1ac5cd6",
    "date": "2026-02-18",
    "title": "Fix touch tap mining and make placement VFX visible"
  },
  "history": [
    {
      "hash": "2e45f606b5e04176d0da115f37e29116124b522b",
      "shortHash": "2e45f60",
      "date": "2026-02-18",
      "title": "Simplify touch HUD and switch to swipe-look camera"
    },
    {
      "hash": "ab1beef7a85f97ef8c143334c458ec9b586f543d",
      "shortHash": "ab1beef",
      "date": "2026-02-18",
      "title": "Simplify in-game HUD and reduce overlay controls"
    },
    {
      "hash": "dc981d6a09fa146a25c150da576ad53841c6c89a",
      "shortHash": "dc981d6",
      "date": "2026-02-18",
      "title": "Update TODO with completion and pushed commit refs"
    },
    {
      "hash": "bae96d5f74f5d2d305029bf78bc926a310f21363",
      "shortHash": "bae96d5",
      "date": "2026-02-18",
      "title": "Add texture/audio assets and QA capture workflow"
    },
    {
      "hash": "e59d179094b50d7c821e133979d9a7d432abeaca",
      "shortHash": "e59d179",
      "date": "2026-02-18",
      "title": "Refactor core game runtime and add shared debug renderer"
    },
    {
      "hash": "fb6e6b87800fdc208de930b95ee20e87eb32d1e9",
      "shortHash": "fb6e6b8",
      "date": "2026-02-17",
      "title": "feat: rebuild voxel game and fix sites portrait layout"
    },
    {
      "hash": "8f822e3464d9b81ab28cd17bce56db7b07be27e7",
      "shortHash": "8f822e3",
      "date": "2026-02-16",
      "title": "Merge remote main and integrate PR #10 into main"
    },
    {
      "hash": "ad1d1561967a8486f03b127e249ac229072667f2",
      "shortHash": "ad1d156",
      "date": "2026-02-16",
      "title": "Refine Stonehenge world generation and monument research panel"
    },
    {
      "hash": "4b3871d68a2978d534085a9cfbfe8b586cfe99d9",
      "shortHash": "4b3871d",
      "date": "2026-02-16",
      "title": "Expand Stonehenge world with classic controls and monument map"
    },
    {
      "hash": "197fc3db71488ce5e113023ccf3b2a5339d216ab",
      "shortHash": "197fc3d",
      "date": "2026-02-16",
      "title": "Add /sites timeline experience, migrate galleries, and switch to adapter-auto"
    },
    {
      "hash": "50851770d7aa5f575ef732b42a4dc2a25329b7a7",
      "shortHash": "5085177",
      "date": "2026-02-16",
      "title": "Merge pull request #12 from max1vol/codex/fix-merge-conflicts-in-svelte-code-j9s56d"
    },
    {
      "hash": "46e20d4ef5e0e52c8d09ee1c82b4850535881945",
      "shortHash": "46e20d4",
      "date": "2026-02-16",
      "title": "Resolve Svelte merge conflict choices in world data"
    },
    {
      "hash": "7cc39e86c9e987caf1389f498f1463c19d3ca090",
      "shortHash": "7cc39e8",
      "date": "2026-02-16",
      "title": "Merge pull request #11 from max1vol/codex/fix-merge-conflicts-in-svelte-code"
    },
    {
      "hash": "c5c46e07dfaab9bef3e90ba247be628df7079716",
      "shortHash": "c5c46e0",
      "date": "2026-02-16",
      "title": "Resolve Svelte merge conflicts for expanded monument world"
    },
    {
      "hash": "0840a3ca766c6060610bb41c2ab02a22b88aba29",
      "shortHash": "0840a3c",
      "date": "2026-02-16",
      "title": "Merge pull request #9 from max1vol/codex/fix-movement-and-interaction-bugs"
    },
    {
      "hash": "4205ac5f57d0613d8ae6dc5b1dd26c0b06581aee",
      "shortHash": "4205ac5",
      "date": "2026-02-16",
      "title": "Fix movement and mining without pointer lock"
    },
    {
      "hash": "b5d733dc23db983e195a0f058e2ea60d4838d40e",
      "shortHash": "b5d733d",
      "date": "2026-02-16",
      "title": "Add tmux game launch reminder instructions"
    },
    {
      "hash": "1c4d7a7ec995e399edc6bd5bc30485273137d44e",
      "shortHash": "1c4d7a7",
      "date": "2026-02-15",
      "title": "Merge pull request #8 from max1vol/codex/convert-to-3d-game-and-check-for-bugs"
    },
    {
      "hash": "7784b59807f8da950cdf21f057e1a68dc290a047",
      "shortHash": "7784b59",
      "date": "2026-02-15",
      "title": "Improve 3D loading safeguards to prevent blackout screens"
    }
  ]
};
