// Generated by scripts/generate_version_snapshot.mjs. Do not edit manually.

export interface VersionChangelogEntry {
  hash: string;
  shortHash: string;
  date: string;
  timestamp: string;
  unixTime: number;
  title: string;
}

export interface VersionSnapshot {
  generatedAt: string;
  packageVersion: string;
  commitHash: string;
  commitShort: string;
  branch: string;
  describe: string;
  label: string;
  latest: VersionChangelogEntry | null;
  history: VersionChangelogEntry[];
}

export const VERSION_SNAPSHOT: VersionSnapshot = {
  "generatedAt": "2026-02-19T16:13:44.581Z",
  "packageVersion": "0.1.0",
  "commitHash": "ffe99aef78025d59ee61a78f4e9d90cc6fed85eb",
  "commitShort": "ffe99ae",
  "branch": "main",
  "describe": "ffe99ae-dirty",
  "label": "v0.1.0 (ffe99ae-dirty)",
  "latest": {
    "hash": "ffe99aef78025d59ee61a78f4e9d90cc6fed85eb",
    "shortHash": "ffe99ae",
    "date": "2026-02-19",
    "timestamp": "2026-02-19T05:02:32-08:00",
    "unixTime": 1771506152,
    "title": "Apply latest touch override and iPhone hotbar safe-area verification"
  },
  "history": [
    {
      "hash": "941e69c08de789cf3652955c14cd8bb6e67c4457",
      "shortHash": "941e69c",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T12:13:31+00:00",
      "unixTime": 1771503211,
      "title": "Merge branch 'origin-main-ssh2'"
    },
    {
      "hash": "7974ce4040855fcb3c9d2fcbe12b0a442c7ced1f",
      "shortHash": "7974ce4",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T12:12:25+00:00",
      "unixTime": 1771503145,
      "title": "Add sourced construction data and expand site galleries with per-image sources"
    },
    {
      "hash": "9e148bf14282b8e09853e8df7c206ff57914a8c8",
      "shortHash": "9e148bf",
      "date": "2026-02-19",
      "timestamp": "2026-02-19T01:44:00-08:00",
      "unixTime": 1771494240,
      "title": "Implement touch targeting parity and Stonehenge standing-stone QA pass"
    },
    {
      "hash": "52a587127a00d93fe167440089fcbc29e265a461",
      "shortHash": "52a5871",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T21:21:08-08:00",
      "unixTime": 1771478468,
      "title": "Finalize monument realms QA pass and capture proofs"
    },
    {
      "hash": "0db530c0b67c0ac47855c114170958ce2d41b3c8",
      "shortHash": "0db530c",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T04:34:48-08:00",
      "unixTime": 1771418088,
      "title": "Replace BGM, add /version route, and fix safe-area HUD QA"
    },
    {
      "hash": "1ac5cd64fdd4c11488509a6f858ee3ec40dcedef",
      "shortHash": "1ac5cd6",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T03:48:29-08:00",
      "unixTime": 1771415309,
      "title": "Fix touch tap mining and make placement VFX visible"
    },
    {
      "hash": "2e45f606b5e04176d0da115f37e29116124b522b",
      "shortHash": "2e45f60",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T02:35:54-08:00",
      "unixTime": 1771410954,
      "title": "Simplify touch HUD and switch to swipe-look camera"
    },
    {
      "hash": "ab1beef7a85f97ef8c143334c458ec9b586f543d",
      "shortHash": "ab1beef",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T02:20:25-08:00",
      "unixTime": 1771410025,
      "title": "Simplify in-game HUD and reduce overlay controls"
    },
    {
      "hash": "dc981d6a09fa146a25c150da576ad53841c6c89a",
      "shortHash": "dc981d6",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T01:48:24-08:00",
      "unixTime": 1771408104,
      "title": "Update TODO with completion and pushed commit refs"
    },
    {
      "hash": "bae96d5f74f5d2d305029bf78bc926a310f21363",
      "shortHash": "bae96d5",
      "date": "2026-02-18",
      "timestamp": "2026-02-18T01:47:16-08:00",
      "unixTime": 1771408036,
      "title": "Add texture/audio assets and QA capture workflow"
    }
  ]
};
